[package]
name = "skip-project"
version = "0.0.1"
edition = "2024"

[workspace]
resolver = "3"
members = ["skip-skia", "skip"]

[workspace.dependencies]
skip = { path = "skip" }
skip-skia = { path = "skip-skia" }
winit = "0.30.13"

[dependencies]
skip.workspace = true
skip-skia.workspace = true
winit.workspace = true
